name: iOS Starter Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test Default Scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default_scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default_scheme | cat > default
          echo "Using default scheme: $default_scheme"

      - name: Build and Test
        env:
          SCHEME: ${{ env.DEFAULT_SCHEME || 'default' }}
          PLATFORM: 'iOS'
        run: |
          device='Any iOS Device'
          if [ "$SCHEME" = default ]; then SCHEME=$(cat default); fi
          if [ -d *.xcworkspace ]; then
            FILETYPE='workspace'
            FILE_TO_BUILD=$(ls -A | grep -i \\.xcworkspace\$ | awk '{$1=$1;print}')
          else
            FILETYPE='project'
            FILE_TO_BUILD=$(ls -A | grep -i \\.xcodeproj\$ | awk '{$1=$1;print}')
          fi
          FILE_TO_BUILD=$(echo $FILE_TO_BUILD | awk '{$1=$1;print}')
          xcodebuild build-for-testing -scheme "$SCHEME" -$FILETYPE "$FILE_TO_BUILD" -destination "generic/platform=iOS"
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to App Center
        uses: microsoft/appcenter-action@v4
        with:
          app_secret: ${{ secrets.APP_CENTER_SECRET }}
          app_name: 'Football Discovery'
          file: '**/*.ipa'
          groups: 'Collaborators'
          release_notes: 'New iOS build released'
          destination_type: 'groups'
